mysql:
  user: "telegram_exchange_user"
  password: "mgstudio884"
  host: "localhost"
  port: 3306
  dbname: "telegram_exchange_bot"

telegram:
  token: "8323841909:AAEfAGnrIOzqpRCdF-Mxf64dIaQF4g_QbLk"
  debug: true

etherscan_api_key: "G3ozx5xtEqGAGi3VdsQGKGHxuwqSJDTn38vEUEREQweQ"
